# Generated by Django 6.0.1 on 2026-06-23 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="store_images/", verbose_name="Store Image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Image",
                "verbose_name_plural": "Store Images",
                "db_table": "store_images",
                "ordering": ["created_at"],
            },
        ),
    ]
