# Generated by Django 6.0.1 on 2026-06-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_storeimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="commercial_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre Comercial",
                max_length=200,
                null=True,
                verbose_name="Commercial Name",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="legal_representative",
            field=models.CharField(
                blank=True,
                help_text="Representante Legal",
                max_length=200,
                null=True,
                verbose_name="Legal Representative",
            ),
        ),
    ]
