# Generated by Django 6.0.1 on 2026-06-25 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productmodel_minimum_price_to_sell"),
        ("store", "0003_store_commercial_name_store_legal_representative"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="avail_all_models",
            field=models.BooleanField(
                default=False,
                help_text="If checked, all product models will be available for this store.",
                verbose_name="Available All Models",
            ),
        ),
        migrations.CreateModel(
            name="StoreProductAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("stock_qty", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_availabilities",
                        to="products.productmodel",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_availabilities",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Product Availability",
                "verbose_name_plural": "Store Product Availabilities",
                "db_table": "store_product_availabilities",
                "ordering": ["-created_at"],
                "unique_together": {("store", "product_model")},
            },
        ),
    ]
