# Generated by Django 6.0.1 on 2026-07-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0029_customerloanledgerentry_and_more"),
        ("store", "0004_store_avail_all_models_storeproductavailability"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="accounting_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="finance.accountingcode",
                verbose_name="Accounting Code",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store",
                to="finance.vendor",
                verbose_name="Linked Vendor",
            ),
        ),
    ]
