# Generated by Django 5.2.4 on 2025-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='credit_application',
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='max_installment_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly installment (30% of income)', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='PaymentRecord',
        ),
    ]
