# Generated by Django 5.1.4 on 2025-10-29 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=64, unique=True)),
                ('employer', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
