# Generated by Django 5.1.4 on 2025-10-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditconfig',
            name='apc_approval_threshold',
        ),
        migrations.AddField(
            model_name='creditconfig',
            name='tier_a_min_score',
            field=models.IntegerField(default=600, help_text='Minimum APC score for Tier A'),
        ),
        migrations.AddField(
            model_name='creditconfig',
            name='tier_b_min_score',
            field=models.IntegerField(default=550, help_text='Minimum APC score for Tier B'),
        ),
        migrations.AddField(
            model_name='creditconfig',
            name='tier_c_min_score',
            field=models.IntegerField(default=500, help_text='Minimum APC score for Tier C'),
        ),
    ]
