# Generated by Django 5.1.4 on 2025-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_creditconfig_apc_approval_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIncomeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='income_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
