# Generated by Django 5.1.4 on 2025-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customerincomefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
