# Generated by Django 6.0.1 on 2026-06-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_customer_otp_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditscore",
            name="bureau_recommendation",
            field=models.TextField(
                blank=True, help_text="Bureau recommendation notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="creditscore",
            name="existing_loans_count",
            field=models.IntegerField(
                default=0, help_text="Number of existing active loans"
            ),
        ),
        migrations.AddField(
            model_name="creditscore",
            name="existing_monthly_debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Existing monthly debt obligations",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="creditscore",
            name="late_payments_count",
            field=models.IntegerField(
                default=0, help_text="Number of late payments recorded"
            ),
        ),
        migrations.AddField(
            model_name="creditscore",
            name="risk_category",
            field=models.CharField(
                blank=True,
                help_text="e.g. Low Risk, Medium Risk, etc.",
                max_length=50,
                null=True,
            ),
        ),
    ]
