# Generated by Django 6.0.1 on 2026-06-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_creditscore_bureau_recommendation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditapplication",
            name="current_step",
            field=models.IntegerField(
                default=0,
                help_text="Current step index for resuming the application flow",
            ),
        ),
    ]
