# Generated by Django 6.0.1 on 2026-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_creditapplication_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditapplication",
            name="draft_data",
            field=models.JSONField(
                blank=True,
                help_text="JSON draft data containing all frontend form inputs/states",
                null=True,
            ),
        ),
    ]
