# Generated by Django 6.0.1 on 2026-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_creditapplication_draft_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditapplication",
            name="loan_agreement_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF contract for the loan agreement",
                null=True,
                upload_to="loan_agreements/",
            ),
        ),
        migrations.AddField(
            model_name="creditconfig",
            name="loan_agreement_template",
            field=models.TextField(
                blank=True,
                default="================================================================================\n                       LOAN & CREDIT AGREEMENT (PANAMA)\n================================================================================\nThis agreement is entered into on this day {date}\nby and between:\n\nCREDITOR: OLA CREDIT PANAMA, S.A.\nBORROWER: {first_name} {last_name}\nIDENTIFICATION (CEDULA): {cedula}\nEMAIL: {email}\nPHONE: {phone}\n\n1. PRODUCT DESCRIPTION:\n   Brand: {device_brand}\n   Model: {device_model}\n   IMEI: {device_imei}\n   \n2. FINANCING DETAILS:\n   Total Selling Price: ${selling_price} USD\n   Cash Price: ${cash_price} USD\n   Accessories: ${accessories} USD\n   Warranty: ${warranty} USD\n   Insurance: ${insurance} USD\n   Total Value: ${total_price} USD\n   Down Payment Paid: ${actual_down_payment} USD\n   Principal Amount to Finance: ${amount_to_finance} USD\n   Term: {selected_term} Months\n   Installment Frequency: Every {installment_frequency_days} Days\n   Monthly Installment: ${monthly_installment} USD\n   Total Repayment: ${total_amount_payable} USD\n   \n3. PAYMENTS & AMORTIZATION:\n   Borrower agrees to make all payments strictly on or before their due dates\n   in accordance with the generated EMI Schedule. Default on any installment\n   will trigger automated remote locking of the product via Samsung Knox/Device Enrollment systems.\n   \nEMI Repayment Schedule:\n{emi_schedule}\n\nSigned by Borrower: ___________________________\nSigned for Ola Credit: _________________________",
                help_text="HTML or text template for the Loan Agreement. Use placeholders like {first_name}, {last_name}, {cedula}, {emi_schedule}, etc.",
                null=True,
            ),
        ),
    ]
