# Generated by Django 6.0.1 on 2026-06-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_creditapplication_loan_agreement_pdf_and_more"),
        ("products", "0003_alter_productmodel_minimum_price_to_sell"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditapplication",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_applications",
                to="products.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="creditapplication",
            name="identity_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creditapplication",
            name="installment_frequency_days",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="creditapplication",
            name="otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="identityverification",
            name="credit_application",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_verification",
                to="customer.creditapplication",
            ),
        ),
        migrations.AlterField(
            model_name="identityverification",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identity_verifications",
                to="customer.customer",
            ),
        ),
    ]
