# Generated by Django 6.0.1 on 2026-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_alter_deviceenrollment_locking_system_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                    ("BLOCKED", "Blocked"),
                    ("DRAFT", "Draft"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
