# Generated by Django 5.1.4 on 2025-11-19 05:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('province_name', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_analytics', to='store.region')),
            ],
            options={
                'db_table': 'geographic_analytics',
                'ordering': ['-date', '-sales_count'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFunnelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('applications', models.IntegerField(default=0)),
                ('kyc_completed', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('kyc_success_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('approval_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('take_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_analytics', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funnel_analytics', to='store.store')),
            ],
            options={
                'db_table': 'application_funnel_analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'store', 'salesperson')},
            },
        ),
        migrations.CreateModel(
            name='BrandModelAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sales_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_analytics', to='store.store')),
            ],
            options={
                'db_table': 'brand_model_analytics',
                'ordering': ['-date', '-sales_count'],
                'indexes': [models.Index(fields=['date', 'brand_name'], name='brand_model_date_5fa1c5_idx'), models.Index(fields=['date', 'store'], name='brand_model_date_0ba6af_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClerkPerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('applications_created', models.IntegerField(default=0)),
                ('applications_approved', models.IntegerField(default=0)),
                ('approval_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('rank_in_store', models.IntegerField(blank=True, null=True)),
                ('rank_overall', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_performance', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_performance', to='store.store')),
            ],
            options={
                'db_table': 'clerk_performance_analytics',
                'ordering': ['-date', '-total_sales'],
                'unique_together': {('date', 'salesperson')},
            },
        ),
        migrations.CreateModel(
            name='DeviceEnrollmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('lock_base_android', models.IntegerField(default=0)),
                ('lock_android_dlc', models.IntegerField(default=0)),
                ('lock_kpe', models.IntegerField(default=0)),
                ('lock_kg', models.IntegerField(default=0)),
                ('lock_base_android_frp', models.IntegerField(default=0)),
                ('lock_access', models.IntegerField(default=0)),
                ('total_devices_enrolled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_analytics', to='store.store')),
            ],
            options={
                'db_table': 'device_enrollment_analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'store')},
            },
        ),
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_financed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_down_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avg_multiple', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_term_months', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('collections_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_metrics', to='store.store')),
            ],
            options={
                'db_table': 'financial_metrics',
                'ordering': ['-date'],
                'unique_together': {('date', 'store', 'salesperson')},
            },
        ),
        migrations.CreateModel(
            name='FPDAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('fpd_3_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fpd_7_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fpd_15_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('early_inactive_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pay_40_at_60_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_contracts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpd_analytics', to='store.store')),
            ],
            options={
                'db_table': 'fpd_analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'store')},
            },
        ),
        migrations.CreateModel(
            name='HourlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hour', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=10)),
                ('sales_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_analytics', to='store.store')),
            ],
            options={
                'db_table': 'hourly_analytics',
                'ordering': ['-date', 'hour'],
                'unique_together': {('date', 'store', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_sales', models.IntegerField(default=0, help_text='Number of sales')),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('active_stores_count', models.IntegerField(default=0)),
                ('avg_retail_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_finance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('avg_down_payment_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sales_per_active_store', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='store.store')),
            ],
            options={
                'db_table': 'sales_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'store'], name='sales_analy_date_b55e93_idx'), models.Index(fields=['date', 'salesperson'], name='sales_analy_date_0586ce_idx')],
                'unique_together': {('date', 'store', 'salesperson')},
            },
        ),
        migrations.CreateModel(
            name='StoreRetentionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('new_stores', models.IntegerField(default=0)),
                ('existing_stores', models.IntegerField(default=0)),
                ('returning_stores', models.IntegerField(default=0)),
                ('churned_stores', models.IntegerField(default=0)),
                ('net_retention', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_analytics', to='store.store')),
            ],
            options={
                'db_table': 'store_retention_analytics',
                'ordering': ['-date'],
                'unique_together': {('date', 'store')},
            },
        ),
    ]
