# Generated by Django 5.1.4 on 2025-11-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_brandperformancemetrics_dailyfinancemetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpdanalytics',
            name='fpd_15_count',
            field=models.IntegerField(default=0, help_text='Number of contracts in FPD-15'),
        ),
        migrations.AddField(
            model_name='fpdanalytics',
            name='fpd_3_count',
            field=models.IntegerField(default=0, help_text='Number of contracts in FPD-3'),
        ),
        migrations.AddField(
            model_name='fpdanalytics',
            name='fpd_7_count',
            field=models.IntegerField(default=0, help_text='Number of contracts in FPD-7'),
        ),
    ]
