# Generated by Django 5.1.4 on 2025-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_fpdanalytics_fpd_15_count_fpdanalytics_fpd_3_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceenrollmentanalytics',
            name='lock_knox',
            field=models.IntegerField(default=0),
        ),
    ]
