# Generated by Django 5.1.4 on 2025-11-19 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_deviceenrollmentanalytics_lock_knox'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicanalytics',
            name='avg_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
