# Generated by Django 5.1.4 on 2025-11-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_geographicanalytics_avg_amount'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkperformanceanalytics',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clerk_performance', to='store.store'),
        ),
    ]
