# Generated by Django 5.1.4 on 2025-11-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_clerkperformanceanalytics_store'),
        ('products', '0003_alter_productmodel_minimum_price_to_sell'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmodelanalytics',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AddField(
            model_name='brandmodelanalytics',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
        ),
        migrations.AddIndex(
            model_name='brandmodelanalytics',
            index=models.Index(fields=['date', 'brand'], name='brand_model_date_6456ec_idx'),
        ),
        migrations.AddIndex(
            model_name='brandmodelanalytics',
            index=models.Index(fields=['date', 'device'], name='brand_model_date_c6b13f_idx'),
        ),
    ]
