# Generated by Django 6.0.1 on 2026-07-13 06:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0007_brandmodelanalytics_brand_brandmodelanalytics_device_and_more",
        ),
        ("products", "0003_alter_productmodel_minimum_price_to_sell"),
        ("store", "0005_store_accounting_code_store_vendor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_applications", models.IntegerField(default=0)),
                ("approved_applications", models.IntegerField(default=0)),
                ("disbursed_loans", models.IntegerField(default=0)),
                (
                    "total_disbursed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "collections",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("ranking", models.IntegerField(default=0)),
                (
                    "region_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "province_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city_name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "branch_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CollectionAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "emi_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "principal_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "penalty_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "collection_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "recovery_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("missed_payments_count", models.IntegerField(default=0)),
                ("late_payments_count", models.IntegerField(default=0)),
                (
                    "outstanding_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "yappy_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "punto_pago_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "western_union_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_transfer_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "collection_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("new_customers", models.IntegerField(default=0)),
                ("returning_customers", models.IntegerField(default=0)),
                ("repeat_financing_count", models.IntegerField(default=0)),
                ("age_distribution", models.JSONField(default=dict)),
                ("gender_distribution", models.JSONField(default=dict)),
                ("employment_distribution", models.JSONField(default=dict)),
                ("income_distribution", models.JSONField(default=dict)),
                ("credit_score_distribution", models.JSONField(default=dict)),
                (
                    "customer_lifetime_value_avg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customer_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_applications", models.IntegerField(default=0)),
                ("approved_applications", models.IntegerField(default=0)),
                ("rejected_applications", models.IntegerField(default=0)),
                ("pending_applications", models.IntegerField(default=0)),
                ("disbursed_loans", models.IntegerField(default=0)),
                (
                    "total_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_disbursed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_collection",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "processing_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("active_stores", models.IntegerField(default=0)),
                (
                    "sales_per_active_store",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_retail_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_finance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_down_payment_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "kyc_success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "take_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("store_retention_new", models.IntegerField(default=0)),
                ("store_retention_existing", models.IntegerField(default=0)),
                ("store_retention_returning", models.IntegerField(default=0)),
                ("store_retention_churned", models.IntegerField(default=0)),
                ("sales_by_hour_day", models.JSONField(default=dict)),
                ("funnel_stages_count", models.JSONField(default=dict)),
                (
                    "avg_approval_time",
                    models.IntegerField(default=0, help_text="in seconds"),
                ),
                (
                    "avg_disbursement_time",
                    models.IntegerField(default=0, help_text="in seconds"),
                ),
                (
                    "avg_payment_delay",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="in days",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_recovery_time",
                    models.IntegerField(default=0, help_text="in days"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DashboardSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_applications", models.IntegerField(default=0)),
                ("total_customers", models.IntegerField(default=0)),
                ("active_loans", models.IntegerField(default=0)),
                ("closed_loans", models.IntegerField(default=0)),
                ("pending_applications", models.IntegerField(default=0)),
                ("approved_applications", models.IntegerField(default=0)),
                ("rejected_applications", models.IntegerField(default=0)),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "total_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_disbursed",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_collection",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_earned",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "processing_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "collection_today",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "collection_this_month",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_emi_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_overdue_emi",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "par_30",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "par_60",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "par_90",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "npa_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_summary",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DeviceAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("units_sold", models.IntegerField(default=0)),
                (
                    "total_sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_down_payment",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "avg_finance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("lock_base_android", models.IntegerField(default=0)),
                ("lock_dlc", models.IntegerField(default=0)),
                ("lock_kpe", models.IntegerField(default=0)),
                ("lock_kg", models.IntegerField(default=0)),
                ("lock_knox", models.IntegerField(default=0)),
                ("lock_base_android_frp", models.IntegerField(default=0)),
                ("lock_access", models.IntegerField(default=0)),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "device_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("applications", models.IntegerField(default=0)),
                ("approvals", models.IntegerField(default=0)),
                ("sales_count", models.IntegerField(default=0)),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "collections",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "executive_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MerchantAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_applications", models.IntegerField(default=0)),
                ("approved_applications", models.IntegerField(default=0)),
                ("rejected_applications", models.IntegerField(default=0)),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("total_sales", models.IntegerField(default=0)),
                (
                    "total_sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_collections",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "growth_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "merchant_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RiskAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("high_risk_customers_count", models.IntegerField(default=0)),
                ("low_risk_customers_count", models.IntegerField(default=0)),
                ("credit_score_distribution", models.JSONField(default=dict)),
                (
                    "default_probability_avg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("fraud_detected_count", models.IntegerField(default=0)),
                ("early_delinquency_count", models.IntegerField(default=0)),
                ("par_30_count", models.IntegerField(default=0)),
                ("par_60_count", models.IntegerField(default=0)),
                ("par_90_count", models.IntegerField(default=0)),
                (
                    "par_30_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "par_60_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "par_90_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("npa_count", models.IntegerField(default=0)),
                (
                    "npa_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "fpd_3_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "fpd_7_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "fpd_15_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "early_inactive_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "pay_40_at_60_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("fpd_by_oem", models.JSONField(default=dict)),
                ("fpd_by_model", models.JSONField(default=dict)),
                (
                    "recovery_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("recovery_trend", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "risk_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="applicationfunnelanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="applicationfunnelanalytics",
            name="salesperson",
        ),
        migrations.RemoveField(
            model_name="applicationfunnelanalytics",
            name="store",
        ),
        migrations.RemoveIndex(
            model_name="brandmodelanalytics",
            name="brand_model_date_5fa1c5_idx",
        ),
        migrations.RemoveIndex(
            model_name="brandmodelanalytics",
            name="brand_model_date_0ba6af_idx",
        ),
        migrations.RemoveIndex(
            model_name="brandmodelanalytics",
            name="brand_model_date_6456ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="brandmodelanalytics",
            name="brand_model_date_c6b13f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="brandperformancemetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="brandperformancemetrics",
            name="brand_perfo_date_43a77a_idx",
        ),
        migrations.RemoveIndex(
            model_name="brandperformancemetrics",
            name="brand_perfo_brand_i_07e997_idx",
        ),
        migrations.AlterUniqueTogether(
            name="clerkperformanceanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clerkperformanceanalytics",
            name="salesperson",
        ),
        migrations.RemoveField(
            model_name="clerkperformanceanalytics",
            name="store",
        ),
        migrations.AlterUniqueTogether(
            name="dailyfinancemetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="dailyfinancemetrics",
            name="daily_finan_date_6d92ab_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailyfinancemetrics",
            name="daily_finan_date_29695f_idx",
        ),
        migrations.RemoveIndex(
            model_name="dailyfinancemetrics",
            name="daily_finan_created_cab246_idx",
        ),
        migrations.AlterUniqueTogether(
            name="deviceenrollmentanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="deviceenrollmentanalytics",
            name="store",
        ),
        migrations.AlterUniqueTogether(
            name="devicelockperformancemetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="devicelockperformancemetrics",
            name="device_lock_date_3b007d_idx",
        ),
        migrations.RemoveIndex(
            model_name="devicelockperformancemetrics",
            name="device_lock_lock_sy_a29fc5_idx",
        ),
        migrations.AlterUniqueTogether(
            name="financialmetrics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="financialmetrics",
            name="salesperson",
        ),
        migrations.RemoveField(
            model_name="financialmetrics",
            name="store",
        ),
        migrations.AlterUniqueTogether(
            name="fpdanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="fpdanalytics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="geographicanalytics",
            name="region",
        ),
        migrations.AlterUniqueTogether(
            name="geographicperformancemetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="geographicperformancemetrics",
            name="geographic__date_4bac5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="geographicperformancemetrics",
            name="geographic__region__cb26b8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="hourlyanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="hourlyanalytics",
            name="store",
        ),
        migrations.AlterUniqueTogether(
            name="paymentcollectionmetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="paymentcollectionmetrics",
            name="payment_col_date_9a1a67_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentcollectionmetrics",
            name="payment_col_date_c986ec_idx",
        ),
        migrations.AlterUniqueTogether(
            name="productperformancemetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="productperformancemetrics",
            name="product_per_date_1f9a28_idx",
        ),
        migrations.RemoveIndex(
            model_name="productperformancemetrics",
            name="product_per_product_ce611d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="riskanalysismetrics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="riskanalysismetrics",
            name="risk_analys_date_e3cb57_idx",
        ),
        migrations.RemoveIndex(
            model_name="riskanalysismetrics",
            name="risk_analys_risk_ti_b417b2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="salesanalytics",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="salesanalytics",
            name="sales_analy_date_b55e93_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesanalytics",
            name="sales_analy_date_0586ce_idx",
        ),
        migrations.AlterUniqueTogether(
            name="salespersonperformance",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="salespersonperformance",
            name="salesperson_date_aca92e_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespersonperformance",
            name="salesperson_salespe_b0edae_idx",
        ),
        migrations.RemoveIndex(
            model_name="salespersonperformance",
            name="salesperson_store_i_830a9b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="storeretentionanalytics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="storeretentionanalytics",
            name="store",
        ),
        migrations.AddField(
            model_name="branchanalytics",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_analytics_records",
                to="store.store",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyanalytics",
            index=models.Index(fields=["date"], name="daily_analy_date_14b7ba_idx"),
        ),
        migrations.AddField(
            model_name="deviceanalytics",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.brand"
            ),
        ),
        migrations.AddField(
            model_name="deviceanalytics",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.productmodel"
            ),
        ),
        migrations.AddField(
            model_name="executiveanalytics",
            name="executive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executive_analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="executiveanalytics",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.store",
            ),
        ),
        migrations.AddField(
            model_name="merchantanalytics",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchant_analytics_records",
                to="store.store",
            ),
        ),
        migrations.DeleteModel(
            name="ApplicationFunnelAnalytics",
        ),
        migrations.RemoveField(
            model_name="brandmodelanalytics",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="brandmodelanalytics",
            name="device",
        ),
        migrations.RemoveField(
            model_name="brandmodelanalytics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="brandperformancemetrics",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="brandperformancemetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="brandperformancemetrics",
            name="store",
        ),
        migrations.DeleteModel(
            name="ClerkPerformanceAnalytics",
        ),
        migrations.RemoveField(
            model_name="dailyfinancemetrics",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dailyfinancemetrics",
            name="district",
        ),
        migrations.RemoveField(
            model_name="dailyfinancemetrics",
            name="province",
        ),
        migrations.RemoveField(
            model_name="dailyfinancemetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="dailyfinancemetrics",
            name="store",
        ),
        migrations.DeleteModel(
            name="DeviceEnrollmentAnalytics",
        ),
        migrations.RemoveField(
            model_name="devicelockperformancemetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="devicelockperformancemetrics",
            name="store",
        ),
        migrations.DeleteModel(
            name="FinancialMetrics",
        ),
        migrations.DeleteModel(
            name="FPDAnalytics",
        ),
        migrations.DeleteModel(
            name="GeographicAnalytics",
        ),
        migrations.RemoveField(
            model_name="geographicperformancemetrics",
            name="district",
        ),
        migrations.RemoveField(
            model_name="geographicperformancemetrics",
            name="province",
        ),
        migrations.RemoveField(
            model_name="geographicperformancemetrics",
            name="region",
        ),
        migrations.DeleteModel(
            name="HourlyAnalytics",
        ),
        migrations.RemoveField(
            model_name="paymentcollectionmetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="paymentcollectionmetrics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="productperformancemetrics",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productperformancemetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="productperformancemetrics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="riskanalysismetrics",
            name="region",
        ),
        migrations.RemoveField(
            model_name="riskanalysismetrics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="salesanalytics",
            name="salesperson",
        ),
        migrations.RemoveField(
            model_name="salesanalytics",
            name="store",
        ),
        migrations.RemoveField(
            model_name="salespersonperformance",
            name="salesperson",
        ),
        migrations.RemoveField(
            model_name="salespersonperformance",
            name="store",
        ),
        migrations.DeleteModel(
            name="StoreRetentionAnalytics",
        ),
        migrations.AddIndex(
            model_name="branchanalytics",
            index=models.Index(
                fields=["date", "store"], name="branch_anal_date_2b92fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchanalytics",
            index=models.Index(
                fields=["region_name"], name="branch_anal_region__fb0e14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="branchanalytics",
            index=models.Index(
                fields=["city_name"], name="branch_anal_city_na_a4b25a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="branchanalytics",
            unique_together={("date", "store")},
        ),
        migrations.AddIndex(
            model_name="deviceanalytics",
            index=models.Index(
                fields=["date", "brand", "device"], name="device_anal_date_2d922b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deviceanalytics",
            unique_together={("date", "brand", "device")},
        ),
        migrations.AddIndex(
            model_name="executiveanalytics",
            index=models.Index(
                fields=["date", "executive"], name="executive_a_date_f3831a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="executiveanalytics",
            unique_together={("date", "executive")},
        ),
        migrations.AddIndex(
            model_name="merchantanalytics",
            index=models.Index(
                fields=["date", "store"], name="merchant_an_date_c14ac7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="merchantanalytics",
            unique_together={("date", "store")},
        ),
        migrations.DeleteModel(
            name="BrandModelAnalytics",
        ),
        migrations.DeleteModel(
            name="BrandPerformanceMetrics",
        ),
        migrations.DeleteModel(
            name="DailyFinanceMetrics",
        ),
        migrations.DeleteModel(
            name="DeviceLockPerformanceMetrics",
        ),
        migrations.DeleteModel(
            name="GeographicPerformanceMetrics",
        ),
        migrations.DeleteModel(
            name="PaymentCollectionMetrics",
        ),
        migrations.DeleteModel(
            name="ProductPerformanceMetrics",
        ),
        migrations.DeleteModel(
            name="RiskAnalysisMetrics",
        ),
        migrations.DeleteModel(
            name="SalesAnalytics",
        ),
        migrations.DeleteModel(
            name="SalespersonPerformance",
        ),
    ]
