# Generated by Django 5.1.4 on 2025-10-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeplan',
            name='installment_frequency_days',
            field=models.IntegerField(choices=[(10, '10 Days'), (15, '15 Days (Bi-Monthly)'), (30, '30 Days (Monthly)')], default=30, help_text='Installment frequency: 10 days or 15 days (bi-monthly) or 30 days (monthly)'),
        ),
        migrations.CreateModel(
            name='FinancePlanTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('apc_score', models.IntegerField(blank=True, null=True)),
                ('risk_tier', models.CharField(blank=True, choices=[('TIER_A', 'Tier A - Low Risk (APC ≥ 600)'), ('TIER_B', 'Tier B - Medium Risk (APC 550-599)'), ('TIER_C', 'High Risk (APC 500-549)'), ('TIER_D', 'Very High Risk (APC < 500)')], max_length=10, null=True)),
                ('device_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_high_end_device', models.BooleanField(default=False)),
                ('minimum_down_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('actual_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('down_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_to_finance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowed_terms', models.JSONField(default=list)),
                ('selected_term', models.IntegerField(blank=True, choices=[(4, '4 Months'), (6, '6 Months'), (8, '8 Months')], null=True)),
                ('installment_frequency_days', models.IntegerField(choices=[(15, '15 Days (Bi-Monthly)'), (30, '30 Days (Monthly)')], default=30)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_capacity_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('maximum_allowed_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installment_to_income_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payment_capacity_passed', models.BooleanField(default=False)),
                ('conditions_met', models.BooleanField(default=False)),
                ('requires_adjustment', models.BooleanField(default=False)),
                ('adjustment_notes', models.TextField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('score_status', models.CharField(blank=True, choices=[('APPROVED', 'Approved (≥80)'), ('CONDITIONAL', 'Approved with Conditions (60-79)'), ('REJECTED', 'Rejected (<60)')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'term_finance_plans',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='term_financ_custome_9ee080_idx'), models.Index(fields=['risk_tier'], name='term_financ_risk_ti_60b853_idx'), models.Index(fields=['apc_score'], name='term_financ_apc_sco_c6f5a0_idx')],
            },
        ),
    ]
