# Generated by Django 5.1.4 on 2025-10-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_latitude_customer_longitude'),
        ('finance', '0002_financeplan_installment_frequency_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFinancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apc_score', models.IntegerField(help_text='APC score from credit bureau')),
                ('risk_tier', models.CharField(choices=[('TIER_A', 'Tier A - Low Risk (APC ≥ 600)'), ('TIER_B', 'Tier B - Medium Risk (APC 550-599)'), ('TIER_C', 'High Risk (APC 500-549)'), ('TIER_D', 'Very High Risk (APC < 500)')], max_length=10)),
                ('customer_monthly_income', models.DecimalField(decimal_places=2, help_text='Validated or declared monthly income', max_digits=10)),
                ('payment_capacity_factor', models.DecimalField(decimal_places=2, help_text='k factor based on risk tier (0.10-0.30)', max_digits=4)),
                ('maximum_allowed_installment', models.DecimalField(decimal_places=2, help_text='k × monthly_income', max_digits=10)),
                ('minimum_down_payment_percentage', models.DecimalField(decimal_places=2, help_text='Minimum % required based on risk tier', max_digits=5)),
                ('allowed_plans', models.JSONField(blank=True, default=list)),
                ('high_end_extra_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_finance_plan', to='customer.creditapplication')),
                ('credit_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_finance_plans', to='customer.creditscore')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_finance_plans', to='customer.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='FinancePlanTerm',
        ),
    ]
