# Generated by Django 5.1.4 on 2025-10-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_autofinanceplan_delete_financeplanterm'),
        ('products', '0003_alter_productmodel_minimum_price_to_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeplan',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productmodel'),
        ),
    ]
