# Generated by Django 5.1.4 on 2025-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CUSTOMER_CREATED', 'Customer Created'), ('CREDIT_SCORE_CHECKED', 'Credit Score Checked'), ('APC_CONSULTED', 'APC Consulted'), ('IDENTITY_VERIFIED', 'Identity Verified'), ('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_APPROVED', 'Application Approved'), ('APPLICATION_REJECTED', 'Application Rejected'), ('DEVICE_ENROLLED', 'Device Enrolled'), ('PAYMENT_RECEIVED', 'Payment Received'), ('DEVICE_LOCKED', 'Device Locked'), ('DEVICE_UNLOCKED', 'Device Unlocked'), ('AUTO_FINANCE_PLAN_CREATED', 'Auto Finance Plan Created'), ('FINANCE_PLAN_CREATED', 'Finance Plan Created'), ('FINANCE_PLAN_VIEWED', 'Finance Plan Viewed')], max_length=50),
        ),
    ]
