# Generated by Django 5.1.4 on 2025-11-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_months', models.PositiveIntegerField(choices=[(4, '4 Months'), (6, '6 Months'), (8, '8 Months')])),
                ('interval_days', models.PositiveIntegerField(choices=[(15, 'Every 15 Days'), (30, 'Every 30 Days')])),
                ('multiple', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_multiples',
                'ordering': ['term_months', 'interval_days'],
                'unique_together': {('term_months', 'interval_days')},
            },
        ),
    ]
