# Generated by Django 5.1.4 on 2025-11-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_auditlog_action_type'),
        ('finance', '0011_financemultiple'),
    ]

    operations = [
    ]
