# Generated by Django 5.1.4 on 2025-11-09 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='autofinanceplan',
            name='has_finance_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financeplan',
            name='auto_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.autofinanceplan'),
        ),
    ]
