# Generated by Django 5.1.4 on 2025-11-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_autofinanceplan_has_finance_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeplan',
            name='auto_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.autofinanceplan'),
        ),
    ]
