# Generated by Django 5.1.4 on 2025-11-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_financeplan_auto_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeplan',
            name='auto_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.autofinanceplan'),
        ),
    ]
