# Generated by Django 5.1.4 on 2025-11-21 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_otp_verified'),
        ('finance', '0018_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofinanceplan',
            name='credit_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_finance_plan', to='customer.creditapplication'),
        ),
    ]
