# Generated by Django 6.0.1 on 2026-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0019_alter_autofinanceplan_credit_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELLED", "Cancelled"),
                    ("REVERSED", "Reversed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
