# Generated by Django 6.0.1 on 2026-06-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0021_accountingcode_invoice_paymentreceived_ledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_received",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to accounting PaymentReceived record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_records",
                to="finance.paymentreceived",
            ),
        ),
    ]
