# Generated by Django 6.0.1 on 2026-06-22 07:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0022_paymentrecord_payment_received"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax percentage rate (e.g. 7.00 for 7%)",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "taxes",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("PLAN", "Financing Plan EMI"), ("MANUAL", "Manual Invoice")],
                default="PLAN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="line_items",
            field=models.JSONField(
                blank=True, default=list, help_text="Split items for manual invoices"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="finance_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="finance.financeplan",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("swift_code", models.CharField(blank=True, max_length=20, null=True)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=20)),
                ("account_type", models.CharField(default="Bank", max_length=20)),
                ("account_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="finance.accountingcode",
                    ),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ["account_name"],
            },
        ),
    ]
