# Generated by Django 6.0.1 on 2026-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0024_bill_journalentry_vendor_ledgerentry_bill_creditnote_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes or memo", null=True
            ),
        ),
    ]
