# Generated by Django 6.0.1 on 2026-06-26 07:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0025_invoice_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_key",
                    models.CharField(
                        help_text="e.g. min_score, max_debt_ratio, blacklist_check",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=250)),
                (
                    "value",
                    models.CharField(
                        help_text="Parameters like numbers or booleans", max_length=100
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "finance_decision_rules",
            },
        ),
        migrations.CreateModel(
            name="EMIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat Interest / Multiplier"),
                            ("REDUCING", "Reducing Balance EMI"),
                        ],
                        default="FLAT",
                        max_length=20,
                    ),
                ),
                (
                    "processing_fee_default",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                (
                    "insurance_fee_default",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "tax_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.0,
                        help_text="ITBMS Tax in %",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "finance_emi_configurations",
            },
        ),
        migrations.CreateModel(
            name="EmployerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employer_name", models.CharField(max_length=200, unique=True)),
                ("min_employment_duration_months", models.IntegerField(default=6)),
                ("is_blacklisted", models.BooleanField(default=False)),
                (
                    "max_loan_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "finance_employer_rules",
            },
        ),
        migrations.CreateModel(
            name="LoanTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "months",
                    models.IntegerField(
                        help_text="Term in months, e.g. 4, 6, 8, 10, 12", unique=True
                    ),
                ),
                (
                    "fortnights",
                    models.IntegerField(
                        help_text="Number of fortnights, e.g. 8, 12, 16, 20, 24"
                    ),
                ),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Flat interest multiplier, e.g. 3.00 for 12 months",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "finance_loan_terms",
            },
        ),
        migrations.CreateModel(
            name="ReferenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_references", models.IntegerField(default=2)),
                ("require_verification", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "finance_reference_rules",
            },
        ),
        migrations.CreateModel(
            name="RiskTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. TIER_A, TIER_B", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_score", models.IntegerField(blank=True, null=True)),
                ("max_score", models.IntegerField(blank=True, null=True)),
                (
                    "min_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "max_debt_ratio_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Maximum EMI to Income ratio in %",
                        max_digits=5,
                    ),
                ),
                (
                    "min_down_payment_pct",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "max_device_value",
                    models.DecimalField(
                        decimal_places=2, default=1500.0, max_digits=10
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto Approval"),
                            ("FINANCE_ADMIN", "Finance Admin Approval"),
                            ("ADMIN", "Admin Approval"),
                            ("GLOBAL_MANAGER", "Global Manager Approval"),
                        ],
                        default="AUTO",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_risk_tiers",
            },
        ),
        migrations.AddField(
            model_name="emischedule",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Remaining principal balance",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="emischedule",
            name="fees",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Processing/Other fees portion",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="emischedule",
            name="insurance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Insurance fee portion of EMI",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="emischedule",
            name="interest",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Interest portion of EMI",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="emischedule",
            name="principal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Principal portion of EMI",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="accessories",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Accessories total price",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="available_capacity",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Income minus existing monthly debt obligations",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="cash_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Cash price from product model",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="debt_ratio_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Debt ratio percentage applied for this tier",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="insurance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Insurance price",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="max_emi_allowed",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Available capacity multiplied by allowed debt ratio",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Selling price from product model",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total price = selling + insurance + accessories + warranty",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="warranty",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Warranty price", max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="InterestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "interest_rate_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interest rate in % (annual)",
                        max_digits=5,
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "insurance_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "risk_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "loan_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_plans",
                        to="finance.loanterm",
                    ),
                ),
            ],
            options={
                "db_table": "finance_interest_plans",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_down_payment_pct",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=1000.0, max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "risk_tier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_rule",
                        to="finance.risktier",
                    ),
                ),
            ],
            options={
                "db_table": "finance_approval_rules",
            },
        ),
    ]
