# Generated by Django 6.0.1 on 2026-06-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0026_decisionrule_emiconfiguration_employerrule_loanterm_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="financeplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
