# Generated by Django 6.0.1 on 2026-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0027_alter_financeplan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financemultiple",
            name="interval_days",
            field=models.PositiveIntegerField(
                choices=[
                    (3, "Every 3 Days"),
                    (7, "Every 7 Days"),
                    (15, "Every 15 Days"),
                    (30, "Every 30 Days"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="financeplan",
            name="installment_frequency_days",
            field=models.IntegerField(
                choices=[
                    (3, "Twice a week (3 Days)"),
                    (7, "Weekly (7 Days)"),
                    (10, "10 Days"),
                    (15, "15 Days (Bi-Monthly)"),
                    (30, "30 Days (Monthly)"),
                ],
                default=30,
                help_text="Installment frequency: 10 days or 15 days (bi-monthly) or 30 days (monthly)",
            ),
        ),
    ]
