# Generated by Django 6.0.1 on 2026-07-01 08:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0015_alter_customer_status"),
        ("finance", "0028_alter_financemultiple_interval_days_and_more"),
        ("store", "0004_store_avail_all_models_storeproductavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLoanLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("DISBURSEMENT", "Disbursement"),
                            ("EMI_PAYMENT", "EMI Payment"),
                            ("INTEREST_ACCRUAL", "Interest Accrual"),
                            ("PENALTY_CHARGED", "Penalty Charged"),
                            ("WRITE_OFF", "Write Off"),
                            ("REVERSAL", "Reversal"),
                            ("CLOSURE", "Loan Closure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "outstanding_interest",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "outstanding_penalties",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField()),
                ("entry_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_ledger_entries",
                        to="customer.customer",
                    ),
                ),
                (
                    "finance_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_ledger_entries",
                        to="finance.financeplan",
                    ),
                ),
            ],
            options={
                "db_table": "customer_loan_ledger_entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="customer_loan_ledger_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="finance.customerloanledgerentry",
            ),
        ),
        migrations.CreateModel(
            name="LoanDisbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disbursement_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "disbursed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finance_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="finance.financeplan",
                    ),
                ),
            ],
            options={
                "db_table": "loan_disbursements",
                "ordering": ["-disbursed_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="disbursement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="finance.loandisbursement",
            ),
        ),
        migrations.CreateModel(
            name="MerchantLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("SETTLEMENT_CREATION", "Settlement Creation"),
                            ("SETTLEMENT_PAYMENT", "Settlement Payment"),
                            ("CANCELLATION", "Cancellation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField()),
                ("entry_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finance_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merchant_ledger_entries",
                        to="finance.financeplan",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_ledger_entries",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_ledger_entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="merchant_ledger_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="finance.merchantledgerentry",
            ),
        ),
        migrations.CreateModel(
            name="MerchantSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="finance.bankaccount",
                    ),
                ),
                (
                    "finance_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="finance.financeplan",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_settlements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="merchantledgerentry",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchant_ledger_entries",
                to="finance.merchantsettlement",
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="finance.merchantsettlement",
            ),
        ),
    ]
