# Generated by Django 6.0.1 on 2026-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0029_customerloanledgerentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financeplan",
            name="disbursed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of loan disbursement", null=True
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="disbursement_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("DISBURSED", "Disbursed")],
                default="PENDING",
                help_text="Direct disbursement status of the loan",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="financeplan",
            name="loan_account_number",
            field=models.CharField(
                blank=True,
                help_text="Unique Loan Account Number",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
