# Generated by Django 6.0.1 on 2026-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0030_financeplan_disbursed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emischedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("UPCOMING", "Upcoming"),
                    ("DUE", "Due"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("PARTIALLY_PAID", "Partially Paid"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
