# Generated by Django 6.0.1 on 2026-07-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0032_invoice_interest_amount_invoice_penalty_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantsettlement",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements",
                to="finance.bill",
            ),
        ),
    ]
