# Generated by Django 6.0.1 on 2026-07-07 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0035_uncategorizedbankentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="emiconfiguration",
            name="punto_pago_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account linked to Punto Pago payments",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="punto_pago_configs",
                to="finance.bankaccount",
            ),
        ),
    ]
