# Generated by Django 6.0.1 on 2026-07-07 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0036_emiconfiguration_punto_pago_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="emiconfiguration",
            name="western_union_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account linked to Western Union payments",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="western_union_configs",
                to="finance.bankaccount",
            ),
        ),
    ]
