# Generated by Django 6.0.1 on 2026-07-10 06:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0037_emiconfiguration_western_union_bank_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fixed_asset_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("purchase_date", models.DateField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "residual_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("useful_life_years", models.IntegerField(default=5)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("purchase_quantity", models.IntegerField(default=1)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("current_quantity", models.IntegerField(default=1)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "disposal_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("warranty_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "computation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("depreciation_start_date", models.DateField(blank=True, null=True)),
                ("asset_life", models.IntegerField(blank=True, null=True)),
                ("asset_life_unit", models.CharField(default="Years", max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[("Straight-Line", "Straight-Line")],
                        default="Straight-Line",
                        max_length=50,
                    ),
                ),
                (
                    "depreciation_interval",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        default="Monthly",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accumulated_depreciation_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accumulated_depreciation_assets",
                        to="finance.accountingcode",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fixed_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depreciation_expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_expense_assets",
                        to="finance.accountingcode",
                    ),
                ),
                (
                    "fixed_asset_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="finance.accountingcode",
                    ),
                ),
                (
                    "fixed_asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_assets",
                        to="finance.fixedassettype",
                    ),
                ),
            ],
            options={
                "db_table": "fixed_assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepreciationScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_index", models.IntegerField()),
                ("period_date", models.DateField()),
                (
                    "depreciation_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("book_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="depreciation_schedule_entries",
                        to="finance.ledgerentry",
                    ),
                ),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_schedule",
                        to="finance.fixedasset",
                    ),
                ),
            ],
            options={
                "db_table": "depreciation_schedule_entries",
                "ordering": ["period_index"],
            },
        ),
    ]
