# Generated by Django 6.0.1 on 2026-07-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0038_fixedassettype_fixedasset_depreciationscheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_notes",
                to="finance.invoice",
            ),
        ),
    ]
