# Generated by Django 6.0.1 on 2026-07-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0039_creditnote_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="accounts_receivable_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes_ar",
                to="finance.accountingcode",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="debit_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes_debit",
                to="finance.accountingcode",
            ),
        ),
    ]
