# Generated by Django 6.0.1 on 2026-07-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0040_creditnote_accounts_receivable_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountingcode",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent account code",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="finance.accountingcode",
            ),
        ),
        migrations.AlterField(
            model_name="accountingcode",
            name="category",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("REVENUE", "Revenue"),
                    ("EXPENSE", "Expense"),
                    ("Income", "Income"),
                    ("Expense", "Expense"),
                    ("Cash", "Cash"),
                    ("Accounts Receivable", "Accounts Receivable"),
                    ("Fixed Asset", "Fixed Asset"),
                    ("Other Current Asset", "Other Current Asset"),
                    ("Accounts Payable", "Accounts Payable"),
                    ("Other Current Liability", "Other Current Liability"),
                    ("Equity", "Equity"),
                    ("Other Expense", "Other Expense"),
                    ("Other Liability", "Other Liability"),
                    ("Stock", "Stock"),
                    ("Cost Of Goods Sold", "Cost Of Goods Sold"),
                    ("Output Tax", "Output Tax"),
                    ("Input Tax", "Input Tax"),
                    ("Bank", "Bank"),
                    ("Non Current Liability", "Non Current Liability"),
                    ("Other Income", "Other Income"),
                    ("Other Asset", "Other Asset"),
                    ("INCOME", "INCOME"),
                    ("EXPENSE", "EXPENSE"),
                    ("LIABILITY", "LIABILITY"),
                    ("EQUITY", "EQUITY"),
                    ("ncome", "ncome"),
                    ("non current liab", "non current liab"),
                ],
                max_length=100,
            ),
        ),
    ]
