# Generated by Django 6.0.1 on 2026-07-13 08:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0041_accountingcode_parent_alter_accountingcode_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceived",
            name="advance_applied",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
