# Generated by Django 5.1.4 on 2025-10-24 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_remove_customuser_store_id_customuser_store'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeess', to='store.store'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['store_id'], name='custom_user_store_i_cdf226_idx'),
        ),
    ]
