# Generated by Django 5.1.4 on 2025-10-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0006_remove_creditconfig_apc_approval_threshold_and_more'),
        ('finance', '0004_financeplan_device'),
        ('products', '0003_alter_productmodel_minimum_price_to_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEnrollmentCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('device_brand_name', models.CharField(help_text='Brand name from ProductModel (e.g., Samsung, Apple, Xiaomi)', max_length=100)),
                ('enrollment_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('QR_GENERATED', 'QR Code Generated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('enrollment_qr_code', models.TextField(blank=True, help_text='QR code for device enrollment', null=True)),
                ('enrollment_link', models.URLField(blank=True, null=True)),
                ('locking_system', models.CharField(choices=[('KNOX', 'Samsung KNOX'), ('NUOVOPAY', 'NuovoPay'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('locking_system_id', models.CharField(blank=True, help_text='Reference ID from KNOX or NuovoPay', max_length=100, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_applied_at', models.DateTimeField(blank=True, null=True)),
                ('imei_verified', models.BooleanField(default=False)),
                ('device_has_internet', models.BooleanField(default=False, help_text='Device must have internet to complete enrollment')),
                ('enrollment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_failed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('device_model', models.ForeignKey(help_text='Auto-populated from FinancePlan', on_delete=django.db.models.deletion.DO_NOTHING, to='products.productmodel')),
                ('finance_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_enrollment_customer', to='finance.financeplan')),
            ],
            options={
                'db_table': 'device_enrollment_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['imei'], name='device_enro_imei_2f2bc5_idx'), models.Index(fields=['enrollment_status'], name='device_enro_enrollm_ecf8ee_idx'), models.Index(fields=['finance_plan'], name='device_enro_finance_49dde2_idx'), models.Index(fields=['customer'], name='device_enro_custome_fce5ac_idx')],
            },
        ),
    ]
