# Generated by Django 6.0.1 on 2026-07-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceenrollmentcustomer",
            name="locking_system",
            field=models.CharField(
                choices=[
                    ("KNOX", "Samsung KNOX"),
                    ("EQUALITY", "Equality"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="deviceenrollmentcustomer",
            name="locking_system_id",
            field=models.CharField(
                blank=True,
                help_text="Reference ID from KNOX or Equality",
                max_length=100,
                null=True,
            ),
        ),
    ]
