# Generated by Django 5.1.4 on 2025-10-15 08:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productmodel',
            name='product_mod_retail__1bce42_idx',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='retail_price_with_tax',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='maximum price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='minimum_price_to_sell',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, help_text='minimum price', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='suggested Retail price (used for financing calculations)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['suggested_price'], name='product_mod_suggest_d43378_idx'),
        ),
    ]
