# Generated by Django 5.1.4 on 2025-10-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmodel_product_mod_retail__1bce42_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='minimum_price_to_sell',
            field=models.DecimalField(decimal_places=2, help_text='minimum price', max_digits=10),
        ),
    ]
